## @section Global Parameters

##  global -- Global params that are overwritten with umbrella chart
global:

propdoc-frontend:
  enabled: true
  extraEnv:
    - name: API_URL
      value: http://api.test.example.com
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - host: test.example.com
        paths:
          - path: /
            pathType: Prefix

propdoc-ml:
  service:
    port: 8000
  enabled: true
  extraEnv:
    - name: LLM_SOURCE
      value: openai
    - name: QDRANT_HOST
      value: http://qdrant.propdoc.svc.cluster.local:6333
    - name: OPENAI_API_KEY
      value: placeholder

propdoc-backend:
  enabled: true
  config:
    SERVER_PORT: 5000
  service:
    port: 5000
  postgresql:
    primary:
      persistence:
        enabled: true
        size: 8Gi
    auth:
      database: propdoc
      password: placeholder
      username: propdoc
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - host: api.test.example.com
        paths:
          - path: /
            pathType: Prefix
  extraEnv:
    - name: DATABASE_URL
      value: postgresql://propdoc:placeholder@db.propdoc.svc.cluster.local:5432/propdoc
    - name: CELERY_BROKER_URL
      value: redis://:placeholder@redis.propdoc.svc.cluster.local:6379/0
    - name: CELERY_RESULT_BACKEND
      value: redis://:placeholder@redis.propdoc.svc.cluster.local:6379/0

propdoc-celery-worker:
  enabled: true
  extraEnv:
    - name: DATABASE_URL
      value: postgresql://propdoc:placeholder@db.propdoc.svc.cluster.local:5432/propdoc
    - name: CELERY_BROKER_URL
      value: redis://:placeholder@redis.propdoc.svc.cluster.local:6379/0
    - name: CELERY_RESULT_BACKEND
      value: redis://:placeholder@redis.propdoc.svc.cluster.local:6379/0
    - name: HOST
      value: http://ml.propdoc.svc.cluster.local:8000/invoke

redis:
  enabled: true
  auth:
    enabled: true
    password: placeholder

traefik:
  enabled: true
  ports:
    web:
      port: 80
    websecure:
      port: 443
  dashboard:
    enabled: true
    port: 8080

qdrant:
  enabled: true
  service:
    port: 6333
  persistence:
    enabled: true
    size: 8Gi